import enum, uuid
from datetime import datetime, timezone
from sqlalchemy import String, Boolean, DateTime, Float, Integer, ForeignKey, Text, JSON, Enum, Index, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID
from app.db.session import Base

def uid(): return uuid.uuid4()
def now(): return datetime.now(timezone.utc)
class Role(str, enum.Enum): ADMIN="ADMIN"; AUTHORITY="AUTHORITY"; DRIVER="DRIVER"; CITIZEN="CITIZEN"
class BusStatus(str, enum.Enum): ACTIVE="ACTIVE"; INACTIVE="INACTIVE"; MAINTENANCE="MAINTENANCE"; OFFLINE="OFFLINE"
class Density(str, enum.Enum): LOW="LOW"; MEDIUM="MEDIUM"; HIGH="HIGH"; CRITICAL="CRITICAL"
class IncidentStatus(str, enum.Enum): NEW="NEW"; UNDER_REVIEW="UNDER_REVIEW"; VERIFIED="VERIFIED"; ASSIGNED="ASSIGNED"; RESOLVED="RESOLVED"; REJECTED="REJECTED"
class Priority(str, enum.Enum): LOW="LOW"; MEDIUM="MEDIUM"; HIGH="HIGH"; CRITICAL="CRITICAL"
class DefectStatus(str, enum.Enum): DETECTED="DETECTED"; VERIFIED="VERIFIED"; ASSIGNED="ASSIGNED"; IN_PROGRESS="IN_PROGRESS"; RESOLVED="RESOLVED"; REJECTED="REJECTED"
class DetectionType(str, enum.Enum): POTHOLE="POTHOLE"; DAMAGED_ROAD="DAMAGED_ROAD"; WATERLOGGING="WATERLOGGING"; TRAFFIC_SIGN="TRAFFIC_SIGN"; ZEBRA_CROSSING="ZEBRA_CROSSING"; ROAD_DIVIDER="ROAD_DIVIDER"; VEHICLE="VEHICLE"; PEDESTRIAN="PEDESTRIAN"; CHILD_RISK="CHILD_RISK"; TRAFFIC_HAZARD="TRAFFIC_HAZARD"
class VehicleType(str, enum.Enum): CAR="CAR"; BUS="BUS"; TRUCK="TRUCK"; MOTORCYCLE="MOTORCYCLE"; AUTO="AUTO"; BICYCLE="BICYCLE"; OTHER="OTHER"
class EvidenceType(str, enum.Enum): IMAGE="IMAGE"; VIDEO="VIDEO"; FRAME="FRAME"; OCR_RESULT="OCR_RESULT"; AI_RESULT="AI_RESULT"
class IncidentType(str, enum.Enum): POSSIBLE_HIT_AND_RUN="POSSIBLE_HIT_AND_RUN"; DANGEROUS_DRIVING="DANGEROUS_DRIVING"; COLLISION_LIKE_EVENT="COLLISION_LIKE_EVENT"; PEDESTRIAN_RISK="PEDESTRIAN_RISK"; ROAD_HAZARD="ROAD_HAZARD"; OTHER="OTHER"
class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, onupdate=now)
class User(TimestampMixin, Base):
    __tablename__='users'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); name: Mapped[str]=mapped_column(String(160)); email: Mapped[str]=mapped_column(String(255), unique=True, index=True); phone: Mapped[str|None]=mapped_column(String(40)); password_hash: Mapped[str]=mapped_column(Text()); role: Mapped[Role]=mapped_column(Enum(Role), default=Role.CITIZEN); is_active: Mapped[bool]=mapped_column(Boolean, default=True)
class Route(TimestampMixin, Base):
    __tablename__='routes'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); name: Mapped[str]=mapped_column(String(160)); code: Mapped[str]=mapped_column(String(40), unique=True); origin: Mapped[str|None]=mapped_column(String(160)); destination: Mapped[str|None]=mapped_column(String(160))
class Driver(TimestampMixin, Base):
    __tablename__='drivers'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); user_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('users.id'), unique=True); license_number: Mapped[str]=mapped_column(String(80), unique=True)
class Bus(TimestampMixin, Base):
    __tablename__='buses'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); bus_number: Mapped[str]=mapped_column(String(40), unique=True); registration_number: Mapped[str]=mapped_column(String(40), unique=True); route_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), ForeignKey('routes.id'), index=True); driver_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), ForeignKey('drivers.id'), index=True); status: Mapped[BusStatus]=mapped_column(Enum(BusStatus), default=BusStatus.INACTIVE, index=True)
class BusLocation(Base):
    __tablename__='bus_locations'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); bus_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('buses.id'), index=True); latitude: Mapped[float]=mapped_column(Float); longitude: Mapped[float]=mapped_column(Float); speed: Mapped[float|None]=mapped_column(Float); heading: Mapped[float|None]=mapped_column(Float); accuracy: Mapped[float|None]=mapped_column(Float); timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True); client_event_id: Mapped[str|None]=mapped_column(String(100), unique=True)
class Detection(TimestampMixin, Base):
    __tablename__='detections'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); bus_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), ForeignKey('buses.id'), index=True); detection_type: Mapped[DetectionType]=mapped_column(Enum(DetectionType), index=True); confidence: Mapped[float]=mapped_column(Float); latitude: Mapped[float|None]=mapped_column(Float); longitude: Mapped[float|None]=mapped_column(Float); timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True); frame_number: Mapped[int|None]=mapped_column(Integer); evidence_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); model_name: Mapped[str]=mapped_column(String(120)); model_version: Mapped[str]=mapped_column(String(80)); metadata_json: Mapped[dict]=mapped_column('metadata', JSON, default=dict)
class RoadDefect(TimestampMixin, Base):
    __tablename__='road_defects'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); defect_type: Mapped[str]=mapped_column(String(50), index=True); severity: Mapped[str]=mapped_column(String(30)); confidence: Mapped[float]=mapped_column(Float); latitude: Mapped[float]; longitude: Mapped[float]; bus_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), ForeignKey('buses.id'), index=True); evidence_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); status: Mapped[DefectStatus]=mapped_column(Enum(DefectStatus), default=DefectStatus.DETECTED, index=True); detected_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
class Vehicle(Base):
    __tablename__='vehicles'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); vehicle_type: Mapped[VehicleType]=mapped_column(Enum(VehicleType)); tracking_id: Mapped[str|None]=mapped_column(String(100), index=True); plate_number: Mapped[str|None]=mapped_column(String(40), index=True); ocr_confidence: Mapped[float|None]=mapped_column(Float); ocr_status: Mapped[str|None]=mapped_column(String(30))
class VehicleDetection(Base):
    __tablename__='vehicle_detections'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); vehicle_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('vehicles.id'), index=True); bus_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), ForeignKey('buses.id'), index=True); confidence: Mapped[float]=mapped_column(Float); latitude: Mapped[float|None]=mapped_column(Float); longitude: Mapped[float|None]=mapped_column(Float); timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
class TrafficEvent(Base):
    __tablename__='traffic_events'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); cars: Mapped[int]=mapped_column(Integer, default=0); bikes: Mapped[int]=mapped_column(Integer, default=0); buses: Mapped[int]=mapped_column(Integer, default=0); trucks: Mapped[int]=mapped_column(Integer, default=0); autos: Mapped[int]=mapped_column(Integer, default=0); total_vehicles: Mapped[int]=mapped_column(Integer, default=0); traffic_density: Mapped[Density]=mapped_column(Enum(Density)); average_speed: Mapped[float|None]=mapped_column(Float); latitude: Mapped[float]; longitude: Mapped[float]; timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True)
class Incident(TimestampMixin, Base):
    __tablename__='incidents'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); bus_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), ForeignKey('buses.id'), index=True); incident_type: Mapped[IncidentType]=mapped_column(Enum(IncidentType)); priority: Mapped[Priority]=mapped_column(Enum(Priority), index=True); description: Mapped[str|None]=mapped_column(Text()); latitude: Mapped[float]; longitude: Mapped[float]; timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True); vehicle_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); confidence: Mapped[float|None]=mapped_column(Float); status: Mapped[IncidentStatus]=mapped_column(Enum(IncidentStatus), default=IncidentStatus.NEW, index=True); created_by: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('users.id'))
class IncidentEvidence(Base):
    __tablename__='incident_evidence'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); incident_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('incidents.id'), index=True); file_url: Mapped[str]=mapped_column(Text()); file_type: Mapped[EvidenceType]; file_size: Mapped[int]; checksum: Mapped[str|None]=mapped_column(String(128)); captured_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
class CitizenReport(TimestampMixin, Base):
    __tablename__='citizen_reports'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); citizen_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('users.id'), index=True); problem_type: Mapped[str]=mapped_column(String(80)); description: Mapped[str|None]=mapped_column(Text()); latitude: Mapped[float]; longitude: Mapped[float]; status: Mapped[str]=mapped_column(String(30), default='SUBMITTED', index=True); image_url: Mapped[str|None]=mapped_column(Text())
class Notification(Base):
    __tablename__='notifications'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); user_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('users.id'), index=True); title: Mapped[str]=mapped_column(String(200)); body: Mapped[str]=mapped_column(Text()); is_read: Mapped[bool]=mapped_column(Boolean, default=False); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now)
class AuditLog(Base):
    __tablename__='audit_logs'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); user_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True), index=True); action: Mapped[str]=mapped_column(String(100)); resource_type: Mapped[str|None]=mapped_column(String(80)); resource_id: Mapped[str|None]=mapped_column(String(100)); ip_address: Mapped[str|None]=mapped_column(String(64)); timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now, index=True); metadata_json: Mapped[dict]=mapped_column('metadata', JSON, default=dict)
class RefreshToken(Base):
    __tablename__='refresh_tokens'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); user_id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), ForeignKey('users.id'), index=True); token_hash: Mapped[str]=mapped_column(String(128), unique=True); expires_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); revoked: Mapped[bool]=mapped_column(Boolean, default=False)
class SyncEvent(Base):
    __tablename__='sync_events'; id: Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True, default=uid); client_event_id: Mapped[str]=mapped_column(String(100), unique=True); event_type: Mapped[str]=mapped_column(String(60)); received_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now); user_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True))
